name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test_W1_5
      id: test_w1_5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test_W1_5
        setup-command: ''
        command: python3 -m unittest discover -s tests
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_W1_5_RESULTS: "${{steps.test_w1_5.outputs.result}}"
      with:
        runners: test_w1_5
